<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="value">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Quotation">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="ProjectName"/>
              <xs:element type="xs:string" name="OEM"/>
              <xs:element type="xs:int" name="LeadID"/>
              <xs:element type="xs:date" name="OfferDate"/>
              <xs:element type="xs:byte" name="Revision"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="outputCurrency"/>
        <xs:element type="xs:float" name="commercialTotalSales"/>
        <xs:element name="revisionHistory" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="revision"/>
              <xs:element type="xs:date" name="date"/>
              <xs:element type="xs:string" name="description"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
